library(FSA)
setwd("C:/Users/Peuclide/Dropbox/Mysis metapopulations")
d <- read.csv("tray1data.csv",header=TRUE)
view(d)
levels(d$idc)
sr4b <- Subset(d,idc=="sr4b")
ms4b <- Subset(d,idc=="ms4b")
ms4p <- Subset(d,idc=="ms4p")
ms14b <- Subset(d,idc=="ms14b")
ms14p <- Subset(d,idc=="ms14p")
ch14b <- Subset(d,idc=="ch14b")
ch14p <- Subset(d,idc=="ch14p")
sr13b <- Subset(d,idc=="sr13b")
sr13p <- Subset(d,idc=="sr13p")
ch19b <- Subset(d,idc=="ch19b")
ch19p <- Subset(d,idc=="ch19p")
sr20b <- Subset(d,idc=="sr20b")
sr20p <- Subset(d,idc=="sr20p")
ms19b <- Subset(d,idc=="ms19b")
ms19p <- Subset(d,idc=="ms19p")

view(sr4b)
summary(d)
plot(N~C, data=sr4b,pch=17,col="black",xlim=c(-32,-28),ylim=c(12,15.1),main="combined")
points(N~C, data=ms4b,pch=16,col="black")
points(N~C, data=ms4p,pch=1,col="black")
points(N~C, data=sr13b,pch=17,col="red")
points(N~C, data=sr13p,pch=2,col="red")
points(N~C, data=ms14b,pch=16,col="red")
points(N~C, data=ms14p,pch=1,col="red")
points(N~C, data=ch14p,pch=0,col="red")
points(N~C, data=ch14b,pch=15,col="red")
points(N~C, data=sr20b,pch=17,col="blue")
points(N~C, data=sr20p,pch=2,col="blue")
points(N~C, data=ch19b,pch=15,col="blue")
points(N~C, data=ch19p,pch=0,col="blue")
points(N~C, data=ms19b,pch=16,col="blue")
points(N~C, data=ms19p,pch=1,col="blue")
legend("bottomleft",c("Split Rock","Main Site","Cumberland Head"),pch=c(17,16,15))

## benthic=closed, pelagic=open   SR=tiangle(open=2,closed=),
#MS=circle, CH=square (closed=pch=15)   11-4=black 11-14=red 11-19=blue
##benthic vs. pelagic
view(d)
Benthic<- Subset(d,habitat=="B")
Pelagic <- Subset(d,habitat=="P")
plot(N~C,data=Benthic,pch=17)
points(N~C,data=Pelagic,pch=3)
legend("bottomleft",c("Benthic","Pelagic"),pch=c(17,3))
## site specific
view(d)
SR<- Subset(d,site=="SR")
MS <- Subset(d,site=="MS")
CH <- Subset(d,site=="CH")
plot(N~C,data=SR,pch=17)
points(N~C,data=MS,pch=3)
points(N~C,data=CH,pch=1)
legend("bottomleft",c("SR","MS","CH"),pch=c(17,3,1))